language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t mkayhan/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true mkayhan/docker-react npm run test -- --coverage

